"""Nickname generation helpers."""

from __future__ import annotations

import random
from collections.abc import Iterable, Sequence

from .constants import ADJECTIVES, NOUNS


def generate_unique_nickname(
    used_nicknames: Iterable[str],
    *,
    adjectives: Sequence[str] = ADJECTIVES,
    nouns: Sequence[str] = NOUNS,
    separator: str = "",
    number_range: int = 100,
    number_width: int = 2,
    rng: random.Random | None = None,
) -> str:
    randomizer = rng or random
    used = set(used_nicknames)
    total = len(adjectives) * len(nouns) * number_range
    if len(used) >= total:
        raise RuntimeError("No nickname combinations are available")

    while True:
        parts = (
            randomizer.choice(adjectives),
            randomizer.choice(nouns),
            f"{randomizer.randint(0, number_range - 1):0{number_width}d}",
        )
        nickname = separator.join(parts) if separator else "".join(parts)
        if nickname not in used:
            return nickname


MONTHLY_NICKNAME_ADJECTIVES = [
    "Agile",
    "Ancient",
    "Angry",
    "Brave",
    "Bright",
    "Calm",
    "Charming",
    "Clever",
    "Cool",
    "Courageous",
    "Crazy",
    "Creative",
    "Cute",
    "Daring",
    "Delightful",
    "Eager",
    "Enchanting",
    "Energetic",
    "Fancy",
    "Friendly",
    "Funny",
    "Gentle",
    "Glorious",
    "Graceful",
    "Happy",
    "Helpful",
    "Honest",
    "Hungry",
    "Jolly",
    "Kind",
    "Lively",
    "Lucky",
    "Merry",
    "Mighty",
    "Mysterious",
    "Nice",
    "Nimble",
    "Peaceful",
    "Perfect",
    "Playful",
    "Proud",
    "Quick",
    "Quiet",
    "Radiant",
    "Rapid",
    "Rich",
    "Sharp",
    "Shiny",
    "Silent",
    "Silly",
    "Smart",
    "Smiling",
    "Smooth",
    "Soft",
    "Sparkling",
    "Strong",
    "Swift",
    "Thoughtful",
    "Tiny",
    "Victorious",
    "Warm",
    "Wild",
    "Wise",
    "Witty",
    "Zealous",
    "Adventurous",
    "Affectionate",
    "Alert",
    "Ambitious",
    "Amused",
    "Brilliant",
    "Careful",
    "Cheerful",
    "Confident",
    "Cooperative",
    "Courageous",
    "Determined",
    "Diligent",
    "Eager",
    "Elated",
    "Enthusiastic",
    "Excited",
    "Exuberant",
    "Fair",
    "Faithful",
    "Fearless",
    "Frank",
    "Friendly",
    "Funny",
    "Generous",
    "Gentle",
    "Good",
    "Happy",
    "Hardworking",
    "Helpful",
    "Honest",
    "Humorous",
    "Imaginative",
    "Intelligent",
    "Joyful",
]

MONTHLY_NICKNAME_NOUNS = [
    "Antelope",
    "Badger",
    "Bat",
    "Bear",
    "Beaver",
    "Bee",
    "Bird",
    "Butterfly",
    "Camel",
    "Cat",
    "Cheetah",
    "Chicken",
    "Chimpanzee",
    "Cobra",
    "Cougar",
    "Cow",
    "Coyote",
    "Crab",
    "Crocodile",
    "Deer",
    "Dog",
    "Dolphin",
    "Donkey",
    "Duck",
    "Eagle",
    "Elephant",
    "Falcon",
    "Ferret",
    "Fish",
    "Fox",
    "Frog",
    "Giraffe",
    "Goat",
    "Goose",
    "Gorilla",
    "Hamster",
    "Hawk",
    "Hedgehog",
    "Hippo",
    "Horse",
    "Hyena",
    "Jaguar",
    "Kangaroo",
    "Koala",
    "Leopard",
    "Lion",
    "Lizard",
    "Llama",
    "Lobster",
    "Monkey",
    "Moose",
    "Mouse",
    "Octopus",
    "Ostrich",
    "Otter",
    "Owl",
    "Panda",
    "Panther",
    "Parrot",
    "Peacock",
    "Penguin",
    "Pig",
    "Polar Bear",
    "Rabbit",
    "Raccoon",
    "Rat",
    "Raven",
    "Reindeer",
    "Rhinoceros",
    "Seal",
    "Shark",
    "Sheep",
    "Skunk",
    "Sloth",
    "Snake",
    "Spider",
    "Squirrel",
    "Swan",
    "Tiger",
    "Turkey",
    "Turtle",
    "Walrus",
    "Wasp",
    "Weasel",
    "Whale",
    "Wolf",
    "Wombat",
    "Woodpecker",
    "Yak",
    "Zebra",
]
